# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FamousFilmsUsingMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FamousFilmsUsingMVVM
pod 'SJFluidSegmentedControl'
pod "ExpandableLabel" #for the more/less button at the end of the label

end
